apiVersion: v1
kind: Secret
metadata:
    name: oidc
stringData:
    SSO_ENABLED: ENC[AES256_GCM,data:jn034w==,iv:UT9UlQOffwSRd4B1Zoir7hSxIREwczuTLWtfJzjhEmo=,tag:PIUfJ/wEUJ4oztRbClKJZQ==,type:str]
    SSO_ONLY: ENC[AES256_GCM,data:ItlkLA==,iv:meEkZaocLtdcZhk2mr2/PQwgan+1pN6i9OCxy2wmXlo=,tag:Rp0IrfwBE1OMV2h3xoh9/Q==,type:str]
    SSO_SIGNUPS_MATCH_EMAIL: ENC[AES256_GCM,data:F2EPLA==,iv:eMFK4vKTI+JxlRsrgoXtPDzjLB0bDLMdbWhEPnf6604=,tag:rm7lneImyK6ZPj6dwGWaKA==,type:str]
    SSO_AUTHORITY: ENC[AES256_GCM,data:Ap3FX3F3NJUv9hMxuibM0IQOJyHr/8e0MLej,iv:sbWPsSwo4TK1A5bRg00fVABqx+WP35S7eGeNby6j0vg=,tag:OjXRGjOnqEeZ5zfPC9pYng==,type:str]
    SSO_PKCE: ENC[AES256_GCM,data:IvMMKg==,iv:mpYlaOfiw0UxGpWY7z9x/19QiwgFksSE5T7xk+8Y20Q=,tag:KFwg0OburtzprEx2HgAnqw==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:wte6cmlkYWOOylxzWVWLutdPvgn7CXRZSmRT4bJTo95AgmMW,iv:dENG7eUT8HrrOBr0aTvbMQc2auG9qoqM8OUqjcwQj54=,tag:mIOO+Og34R6vzam17D84Eg==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:DtFZdqlYqYWDR9Eirlp0sxhI/PxL+4wYOYORx/qJX+I=,iv:Tkb9k1wCaUQ4xY64utspCEFiVpUNCjSDAyaXD3vALTg=,tag:S3Wm2SF8mMgrxYyTuvoLNQ==,type:str]
sops:
    age:
        - recipient: age1mc6573986ak84qcs9slsel3rahaw8gjseh5f085gyr6zhz6yuu7qqhluwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWGZwM0lxWDYrb1RLMmFQ
            cmQ5OG1yVmM4RDg5TlQzc1NVMzZZa1J0b1NJClY2VzFQN1NnaWJlcmFSUGtTd2NY
            UWliRitYak1kaytaczFJUnR3RDcyUGMKLS0tIENXQmVWM0p3UjFUQ2s5Ty9vSklu
            dlg0WHZNU3lyeEljaFJET2Eva3dXNmsKkghJxuuU+6ozF06cP0VGPM4tl/JJsSkp
            tOTfxMr5E4DwUBxVZHckBhLN5K23544GxbdiawF+dP/woK+frVHmzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T22:59:19Z"
    mac: ENC[AES256_GCM,data:BhDs1Kbnf1AEv4uy1qMdTFcf1/1GDo3EQyLm9WVZfYiGszfQQY8+Iveel8dLGZu32NX90ZLGd5G097mw8l31SyEwQZBLzSPAJs1L5JcPxz8w8uE/epx0eMehx1myfnoTM2GNqbECamldRpbnMZc/Xt7iCZcgGEC2qU1Yym+0iAE=,iv:UMcfoIlLOnS6pRzSgY/CjPHY09K3mX1AOipo8/fja3Y=,tag:ePwNbXUvtm25wzHsHAYuYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: admin-token
stringData:
    #ENC[AES256_GCM,data:dHzXV2zupuYs/06CgPHvsX6++msqY7i+VQo8tAENoBxJ7rD2jcQeWg==,iv:hwZuicz5K8zWhIQmKlK7BzEGZiYgAzaMHgSwCw1ikk0=,tag:ZR6FrJeALTezCgLUNK3WYA==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:DwcWWQ/L8ub3vE3A8Krc1Rhrf13vWbqe,iv:FwxK355v600fQjZKG81wweO1QeXsW8vzFvsZylZ2eD4=,tag:SEK4c5WXbCYDrof03TdFlw==,type:str]
sops:
    age:
        - recipient: age1mc6573986ak84qcs9slsel3rahaw8gjseh5f085gyr6zhz6yuu7qqhluwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWGZwM0lxWDYrb1RLMmFQ
            cmQ5OG1yVmM4RDg5TlQzc1NVMzZZa1J0b1NJClY2VzFQN1NnaWJlcmFSUGtTd2NY
            UWliRitYak1kaytaczFJUnR3RDcyUGMKLS0tIENXQmVWM0p3UjFUQ2s5Ty9vSklu
            dlg0WHZNU3lyeEljaFJET2Eva3dXNmsKkghJxuuU+6ozF06cP0VGPM4tl/JJsSkp
            tOTfxMr5E4DwUBxVZHckBhLN5K23544GxbdiawF+dP/woK+frVHmzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T22:59:19Z"
    mac: ENC[AES256_GCM,data:BhDs1Kbnf1AEv4uy1qMdTFcf1/1GDo3EQyLm9WVZfYiGszfQQY8+Iveel8dLGZu32NX90ZLGd5G097mw8l31SyEwQZBLzSPAJs1L5JcPxz8w8uE/epx0eMehx1myfnoTM2GNqbECamldRpbnMZc/Xt7iCZcgGEC2qU1Yym+0iAE=,iv:UMcfoIlLOnS6pRzSgY/CjPHY09K3mX1AOipo8/fja3Y=,tag:ePwNbXUvtm25wzHsHAYuYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
