apiVersion: v1
kind: Secret
metadata:
    name: immich-database-app
stringData:
    username: ENC[AES256_GCM,data:oO/cBHaQ,iv:iUwQVFmA35LevszTM/sZ9VDoCPDjxnyw1Rr7SjYfII8=,tag:0OUfGzbkfDAC/ZrgE4/O+w==,type:str]
    password: ENC[AES256_GCM,data:HJofbXRzI3qNTndFq47L3k/W,iv:Eu3i/SS/mbW6jQI8eg723zHgIcPBHugXc44yGiyn8UI=,tag:z2QE8wVkIUtubYNKePT9nQ==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1mc6573986ak84qcs9slsel3rahaw8gjseh5f085gyr6zhz6yuu7qqhluwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudGtiVjBSeFRmMVBMak4v
            YXRRSHBSNXhLd2xCNjVSamFPOWp5bUZQMGlVCmRJVHlWcE55U3hocFJLQ09CaG5G
            Tzk4ajJjaHNOa014bFlBTzJEcmFuVDAKLS0tIGJVU3FnOUsxaHN3blNtczJ6dzRW
            R1hsVExLVGN1bEtUcW1FWHkvd1JsWjgKVJPUJUm6xR1whVcS0lLECyUb0OvJaCCp
            c44Bner/lMU8S/GBe5cCRxfWiREMEXrYV28VmGa1D567hHP5N4+8rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T23:24:37Z"
    mac: ENC[AES256_GCM,data:/VqWfqZxnt+GzUj/xbtdifI7VjUpn5QkTYWQEjBSt4dp69hfwLMx1TTvF+Vviow98LzmSgMTb3Mu6xIeQJ0iClgcCJJ0hsvpkhfQcbStLc9D+XUW/zeBpzHPZnWXutUNBIBY8NmKLng/30vtaG5t+tK71pjsEsaIX6R3iOcq3gY=,iv:ph3h9lGEDPhUsPImegau5qDBuQ2x2gwcMNXJtD7hZ7U=,tag:ko02pCQ61ZYPoxEKc0bNOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
