---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-photos
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: photos
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: data
    volumeHandle: photos
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8rn-core
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-zfs-data
  volumeMode: Filesystem
---
apiVersion: zfs.openebs.io/v1
kind: ZFSVolume
metadata:
  name: photos
  namespace: openebs
  finalizers:
    - k8rn/dummy-finalizer
spec:
  capacity: "3985729650688"
  fsType: zfs
  ownerNodeID: k8rn-core
  poolName: data
  volumeType: DATASET
  shared: "yes"
status:
  state: Ready
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photos
spec:
  storageClassName: openebs-zfs-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: immich-photos
