apiVersion: v1
kind: Secret
metadata:
    name: api-key
type: Opaque
stringData:
    apikey: ENC[AES256_GCM,data:y04/oQrPxm/bkdj2umYumC3MEa8IvJgLT2ZOFZSMZRY=,iv:dz1NuJhmc5w+aIZE9/T9J4cZPFEj+lnXMTmcZjldNkA=,tag:MYAVtnHqiEEuncBsY+nrcw==,type:str]
sops:
    age:
        - recipient: age1mc6573986ak84qcs9slsel3rahaw8gjseh5f085gyr6zhz6yuu7qqhluwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSekpDaHRuYm1RNTVWcmlr
            Zno2Y2pxdk9YTjlmUmp0cElqVkZjaG9zREdjCjVKUWIya3RaNlkwWmlhc2pXQk5H
            elVqYTVjVldadzZJdmdBY0lzSVgxUjQKLS0tIGZWd01QdUNwWWtUWjcvRTNrd0FI
            YXBRbTRnb2RsWTR0MEx2U3RqcEdyczAKjZMVcXMGQD0QDsiyhZeYkGqZBM7KPupj
            1KEvebLBidYwNl5Rp61BsKkgmmE6G/jn+mUZFHe3Jm1gSP2yyLfPQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T20:42:36Z"
    mac: ENC[AES256_GCM,data:WcSvorjfjOm7rBm0YCXv2ceWrDcciNpRTZCn9Y4/D7VSPlb9aZCK/WBxfOV5XZdxIclhqVFyymtqBxhBRLTWRoI68diujaG8G79ydaxrDM3GAmJGq9JxubR5tbcna2yyH1qBDVzVyshYo52FLzwZ8Et/UnuyRj4vDY5ZTuE35So=,iv:m5IySV1DNyR8H43VfBgJE+bErt+ZCP8kxqeHyDCC0bE=,tag:2upYXbFfWcBor8P8PH2PAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
