---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: observability
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 10m0s
  targetNamespace: observability
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus
      version: 11.8.0
  values:
    config:
      modules:
        kms_service_health:
          prober: grpc
          grpc:
            service: sidero.kms.KMSService
            tls: true
    serviceMonitor:
      enabled: true
      targets:
        - name: unlockr
          url: ${kms_endpoint_domain}:11111
          module: kms_service_health
    prometheusRule:
      enabled: true
      rules:
        - alert: UnlockrDown
          annotations:
            description: "unlockr is unhealthy!"
            summary: "unlockr is unhealthy!"
          expr: |-
            (
              probe_success{target="unlockr"} != 1
            )
          for: 10m
          labels:
            severity: critical
