---
apiVersion: openebs.io/v1beta3
kind: DiskPool
metadata:
  name: w-eq12-0
  namespace: openebs
spec:
  disks:
    - "uring:///dev/mapper/luks2-${openebs_diskpool_partition_label}"
  node: k8rn-w-eq12-0
